<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="SmartCode.App" Version="2.2.58" />
    <PackageReference Include="SmartCode.Generator" Version="2.2.58" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.Pdm\Bing.Pdm.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Templates\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="HandlebarsTemplates\Java\Entity.hbs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
